server:
  port: 8181

spring:
  application:
    name: document-services

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org.springframework: DEBUG


security:
  oauth2:
    resource:
      jwt:
        # Tells the JWT framework to fetch the public key from the authorization server during startup
        # Note: The authorization server needs to be running...
        key-uri: http://localhost:9999/uaa/oauth/token_key

  basic:
    enabled: false