server:
  port: 8182

spring:

  application:
    name: user-services
  cloud:
    cluster:
      zookeeper:
        leader:
          enabled: true
        connect: 192.168.99.100:2181
      leader:
        enabled: true