spring.application.name: gateway

server.port: 8082

security:
  ignored: /favicon.ico
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
      scope: openid,read,write
    resource:
      #token-info-uri: http://localhost:8080/uaa/token_key
      #jwt.keyUri: http://localhost:8080/uaa/token_key
      user-info-uri: http://localhost:8080/uaa/me