server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    cluster:
      zookeeper:
        leader:
          enabled: true
        connect: 192.168.99.100:2181
      leader:
        enabled: true
    zookeeper:
      connect-string: 192.168.99.100:2181

security:
  ignored: /favicon.ico
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
      scope: openid,read,write
    resource:
      #token-info-uri: http://localhost:8080/uaa/token_key
      #jwt.keyUri: http://localhost:8080/uaa/token_key
      #user-info-uri: http://localhost:8080/uaa/me
      user-info-uri: //auth-server/uaa/me