server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  instance:
    prefer-ip-address: true
    appname: gateway
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    leaseRenewalIntervalInSeconds: 2
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
    eureka:
        enabled: true

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

feign:
  hystrix:
     enabled: false

security:
  ignored: /favicon.ico
  user:
      password: none
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
      scope: openid,read,write
    resource:
      user-info-uri: http://auth-server/uaa/user

zuul:
  routes:
    auth:
      path: /uaa/**
      url: http://localhost:9999/uaa/
      sensitive-headers: