logging:
  level:
    org.springframework.boot.actuate.audit.listener.AuditListener: DEBUG

server:
  port: 8888

spring:
  application:
    name: gateway

eureka:
  instance:
    prefer-ip-address: true
    appname: gateway
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    leaseRenewalIntervalInSeconds: 2
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
    eureka:
        enabled: true

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

feign:
  hystrix:
     enabled: false

security:
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://auth-server/uaa/user
      prefer-token-info: true
      jwt:
              # Tells the JWT framework to fetch the public key from the authorization server during startup
              # Note: The authorization server needs to be running...
              key-uri: http://localhost:9999/uaa/oauth/token_key
  sessions: always


zuul:
  routes:
    document:
      path: /api/documents/**
      url: http://localhost:8181/api/documents/
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user

