server:
  port: 8761

spring:
  application:
    name: registry

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: false
