server:
  port: ${SERVICE_PORT:8181}

undertow:
    buffer-size: 16000

management.security.enabled: false

spring:
  rabbitmq:
      addresses: 192.168.99.100
      port: 5672
      username: guest
      password: guest

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 7
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
      cluster: default
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      jwt:
        # Tells the JWT framework to fetch the public key from the authorization server during startup
        # Note: The authorization server needs to be running...
        key-uri: http://localhost:9999/uaa/oauth/token_key

  basic:
    enabled: false