server:
  port: ${SERVICE_PORT:8888}
  undertow:
        buffer-size: 16000

eureka:
  instance:
    registryFetchIntervalSeconds: 1
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true

security:
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://auth-server/uaa/user
      prefer-token-info: true
      jwt:
              # Tells the JWT framework to fetch the public key from the authorization server during startup
              # Note: The authorization server needs to be running...
              key-uri: http://localhost:9999/uaa/oauth/token_key
  sessions: always


zuul:
  routes:
    document:
      path: /api/documents/**
      serviceId: docs-services
      stripPrefix: false
      sensitiveHeaders: '*'
    user:
      path: /user/**
      serviceId: auth-server
      stripPrefix: false
      sensitiveHeaders: '*'


ribbon:
    eureka:
        enabled: true
