server:
  port: 11111
  undertow:
    buffer-size: 16000

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
  profiles:
    active: native
  application:
    name: config-server
  rabbitmq:
    addresses: 192.168.99.100
    port: 5672
    username: guest
    password: guest


management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/