server:
  port: 11111
  undertow:
    buffer-size: 16000

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
  profiles:
    active: native
  application:
    name: config-server

management:
  security:
    enabled: false
logging:
  level.org.springframework: debug

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/